name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords
          python -m nltk.downloader wordnet

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -v tests/test_extraction.py --junitxml=reports/test-results-extraction.xml
          pytest -v tests/test_preprocessing.py --junitxml=reports/test-results-preprocessing.xml
          pytest -v tests/test_file_saver.py --junitxml=reports/test-results-file-saver.xml
          pytest -v tests/test_main.py --junitxml=reports/test-results-main.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/*.xml

      - name: Notify on Failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log('No pull request found. Skipping comment (push event).');
              return;
            }
            const issueNumber = pr.number;
            const message = '🚨 The build has failed. Please review the test results.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });

      - name: Notify on Success
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log('No pull request found. Skipping comment (push event).');
              return;
            }
            const issueNumber = pr.number;
            const message = '✅ The build has succeeded. All tests passed!';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });

      - name: Notify on Skipped
        if: ${{ cancelled() }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log('No pull request found. Skipping comment (push event).');
              return;
            }
            const issueNumber = pr.number;
            const message = '⏸️ The build was skipped. Please check the logs for more details.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });
